### ISSUE TITLE
The Account page does not have Traditional Chinese

### ISSUE THREAD

**Issue by hink-jianqiang** [keycloakify/keycloakify#749] opened 2024-12-26 11:21 UTC
After I added Chinese Traditional, I entered the account page, but it showed English

**Comment by garronej** [comment] 2024-12-26 11:54
Hello,

Please provide more details, what account theme? Single-Page or Multi-Page

**Comment by hink-jianqiang** [comment] 2024-12-27 01:17
> Hello,
> 
> Please provide more details, what account theme? Single-Page or Multi-Page

![image](https://github.com/user-attachments/assets/76de5097-a2ac-427e-a7f2-300f218c052f)

Multi-Page, I see that the source code is missing zh-TW.ts, which causes the custom theme to display abnormally. How can I solve this problem? Thank you
![image](https://github.com/user-attachments/assets/ccffe6d8-6452-4375-a284-afa7bab87de7)
![image](https://github.com/user-attachments/assets/c1ce2beb-61ec-4220-9838-c2be2519f6ed)

**Comment by garronej** [comment] 2024-12-27 02:51
Here you go: https://docs.keycloakify.dev/i18n/adding-support-for-extra-languages

**Comment by hink-jianqiang** [comment] 2024-12-27 03:16
> Here you go: https://docs.keycloakify.dev/i18n/adding-support-for-extra-languages
I tried to do this, but the following message was prompted. When I used withCustomTranslations, it prompted that this type does not exist
![image](https://github.com/user-attachments/assets/72544641-d3f2-457c-b059-1f808be6ffe0)
![image](https://github.com/user-attachments/assets/fcdcf9ab-4a96-4dce-bb85-ca5889c10374)

**Comment by garronej** [comment] 2024-12-27 04:04
Yes, this is the expected behavior.

It seems you’ve made three mistakes:  

1. **Missing `.withExtraLanguages` Implementation**  
   You need to implement `.withExtraLanguages` and add `zh-TW`. Your commented-out code looks fine, so I’m not sure why you’ve commented it out. That’s the correct way to add support for an extra language.

2. **Misuse of `withCustomTranslations`**  
   You’re using `withCustomTranslations` incorrectly. This function is designed to define extra keys or translations specific to your theme, not to provide the entire set of base messages.

3. **Incorrect Messages Target**  
   You’re implementing messages for the login UI, but you should be working on messages for the account UI. Check the top of your file; you likely have:  
   ```ts  
   import { i18nBuilder } from "keycloakify/login";  
   ```  
   Instead, you should have:  
   ```ts  
   import { i18nBuilder } from "keycloakify/account";  
   ```

I hope this helps clarify things!

**Comment by hink-jianqiang** [comment] 2024-12-27 06:28
> Yes, this is the expected behavior.
> 
> It seems you’ve made three mistakes:
> 
> 1. **Missing `.withExtraLanguages` Implementation**
>    You need to implement `.withExtraLanguages` and add `zh-TW`. Your commented-out code looks fine, so I’m not sure why you’ve commented it out. That’s the correct way to add support for an extra language.
> 2. **Misuse of `withCustomTranslations`**
>    You’re using `withCustomTranslations` incorrectly. This function is designed to define extra keys or translations specific to your theme, not to provide the entire set of base messages.
> 3. **Incorrect Messages Target**
>    You’re implementing messages for the login UI, but you should be working on messages for the account UI. Check the top of your file; you likely have:
>    ```ts
>    import { i18nBuilder } from "keycloakify/login";  
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Instead, you should have:
>    ```ts
>    import { i18nBuilder } from "keycloakify/account";  
>    ```
> 
> I hope this helps clarify things!

Thank you very much. Is there any plan to add traditional Chinese support to the account page? Because when I don't add extra language, the login page is normal. And my account page still has the following small problems
![image](https://github.com/user-attachments/assets/ad5d0614-d932-4efc-90ee-50cf817c5af0)
![image](https://github.com/user-attachments/assets/42c86cd2-4ae7-48ee-866e-0b62ee3c0fdd)
![image](https://github.com/user-attachments/assets/8c3290ca-d7ce-420d-b951-33eee94dd81c)

**Comment by garronej** [comment] 2024-12-27 14:28
> And my account page still has the following small problems  

For `zh-TW` appearing, of course it's the case because you've defined it as label! Use:
```ts
.withExtraLanguages({
   "zh-TW": { 
       label: "繁體中文（台灣）", 
```

For the `Account` appearing in plain, this mean that you do not have provided a translation for the `account` message key.  
https://github.com/keycloakify/keycloakify/blob/cd1b55b850b8acb6bfa3ae081b301f88092e3d54/src/account/Template.tsx#L88

**Comment by hink-jianqiang** [comment] 2024-12-28 01:46
> > And my account page still has the following small problems
> 
> For `zh-TW` appearing, of course it's the case because you've defined it as label! Use:
> 
> ```ts
> .withExtraLanguages({
>    "zh-TW": { 
>        label: "繁體中文（台灣）", 
> ```
> 
> For the `Account` appearing in plain, this mean that you do not have provided a translation for the `account` message key.
> 
> https://github.com/keycloakify/keycloakify/blob/cd1b55b850b8acb6bfa3ae081b301f88092e3d54/src/account/Template.tsx#L88

Thank you for your assistance

**Comment by garronej** [comment] 2024-12-28 01:56
You're wellcome!  

Can we close this, have you managed to make it work?

**Comment by hink-jianqiang** [comment] 2024-12-28 03:12
> You're wellcome!
> 
> Can we close this, have you managed to make it work?

yes

**Closed** 2024-12-28 03:14 UTC
