### ISSUE TITLE
updating minor build fails for vite and nx monorepo

### ISSUE THREAD

**Issue by satanshiro** [keycloakify/keycloakify#550] opened 2024-05-15 09:51 UTC
Updating keycloakify with minor version (probably fails from 9.4) the build fails.
so looking at documentation 
I migrated to vite and looked at the starter project but i still have problems this is my error 
<img width="1086" alt="image" src="https://github.com/keycloakify/keycloakify/assets/38865738/e1918ae5-2e82-4992-95d1-1dc312ed1dcd">
and this vite config 
<img width="449" alt="image" src="https://github.com/keycloakify/keycloakify/assets/38865738/2813ba89-eccd-427f-bb03-a32f9bd1ade4">
running npx keycloakify --project apps/platform gives me this error, it seems keycloakify thinks node modules are not in the root folder but rather in the child folder even though i specified  in cli --project 
<img width="325" alt="image" src="https://github.com/keycloakify/keycloakify/assets/38865738/fea99b72-e63c-4382-ad9f-dca0ecf1fc55">

**Comment by garronej** [comment] 2024-05-15 10:38
Hello @satanshiro,  

First of the `reactAppBuildDirPath` is not to be provided by you, it's defined by the Vite config. This option is only for Webpack projects. I should remove it from the type.  
After the value you gave to `keycloakifyBuildDirPath` is very unusual. it's usually `./keycloak_dist`.  
Note that you are expected to load the jar file of your theme into Keycloak, nod directly the resources files manually. But I digress.  
On the first screenshot I see `dummy-non-existing-folder` looks like you've run:  

```bash
npx keycloakify -p apps/dummy-non-existing-folder
```

Or something like that...  

If you could produce a reproduction repo it would help. It's hard and time consuming to parse information from screeshots.  

Best

**Comment by satanshiro** [comment] 2024-05-15 11:43
@garronej I very much appreciate your timely answer! sorry for not providing enough information.
I have a nx monorepo setup, vite.config.ts file resides within a child repository (i.e. apps/platform).
when i run nx build:platofrm it builds the app using vite with output dir set to the root folder instead of the inner child path.
I also notice that keycloakify for some reason during build adds a cache file called vite.json. this file unfortunately is created inside the child path (in this case apps/platform) instead of in the root node_modules folder. upon further investigation I tried changing the file so that instead of the build dir showing "dummy-non-existing-folder" i overwrite it with the correct path(maybe keycloakify is not using the outdir provided in vite config) 
<img width="307" alt="image" src="https://github.com/keycloakify/keycloakify/assets/38865738/07076d4c-f2bf-4cd0-a1e8-0493d12ac2eb">
then it seems to work

**Comment by garronej** [comment] 2024-05-16 08:31
PS: I see you're using "oidc-client-ts". Maybe you'd be interested in having a look at https://oidc-spa.dev  
We're still gathering feedbacks and suggestions before launching it officially. If you have any they are very welcome.

**Comment by satanshiro** [comment] 2024-05-16 10:15
The oidc-spa project looks wonderful good job, will consider it thank you. I guess i'll try to reprocude hopefully by today or next week thanks again

**Comment by satanshiro** [comment] 2024-05-16 10:16
ps my vite config is :

**Comment by garronej** [comment] 2024-05-16 14:26
I need to see your vite config

**Comment by garronej** [comment] 2024-05-16 15:07
> The oidc-spa project looks wonderful good job, will consider it thank you.

Thank you 😊 Let me know if you have any suggestion.  

Ok thanks for the aditional info this is definatly worth fixin then because chances are this happen in every NX setup.  
Can you do a search in your codebase for `dummy-non-existing-folder` and`dummy` this if this comes form your configuration?  

Next, could you add a console.log in the Keycloakify vite plugin, build again and show me what you got.  

<img width="1406" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/8e7cc43b-dc6e-46ad-88a6-d44cea0a9ae9">


you'll need to remove `node_modules/.vite` and `node_modules/.cache`

**Comment by satanshiro** [comment] 2024-05-19 12:17
I was unable to find where 'dummy-non-existing-folder' comes from. I can't find it nor in my code base or in the node_modules ir on the web very peculiar hopefuully will happen in the repro.
in regards to why the vite.json in created wrongfully in a the child path folder and not root folder is because 
is the root folder path specified in vite config file as `root: __dirname`  and is later used to instantiate reactAppRoot and cachedir (look at last lines of the log) regardless of where the vite.json file is being created for some reason buildDir is still 'dummy-non-existing-folder', 
the console logs I added
![image](https://github.com/keycloakify/keycloakify/assets/38865738/4dc76f52-a4b5-4b3e-adae-995ae12a17a3)
the results
```bash
outdir ../../dist/apps/platform
build {
  target: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  cssTarget: [ 'es2020', 'edge88', 'firefox78', 'chrome87', 'safari14' ],
  outDir: '../../dist/apps/platform',
  assetsDir: 'assets',
  assetsInlineLimit: 4096,
  cssCodeSplit: true,
  sourcemap: false,
  rollupOptions: { onwarn: [Function: onwarn] },
  minify: 'esbuild',
  terserOptions: {},
  write: true,
  emptyOutDir: null,
  copyPublicDir: true,
  manifest: false,
  lib: false,
  ssr: false,
  ssrManifest: false,
  ssrEmitAssets: false,
  reportCompressedSize: true,
  chunkSizeWarningLimit: 500,
  watch: false,
  commonjsOptions: {
    include: [ /node_modules/ ],
    extensions: [ '.js', '.cjs' ],
    transformMixedEsModules: true
  },
  dynamicImportVarsOptions: { warnOnError: true, exclude: [ /node_modules/ ] },
  modulePreload: { polyfill: true },
  cssMinify: true
}
buildDirPath /Users/orenpassig/Documents/development/frontend/dist/apps/platform
reactAppRoot /Users/orenpassig/Documents/development/frontend/apps/platform
cacheDirPath /Users/orenpassig/Documents/development/frontend/apps/platform/node_modules/.cache/keycloakify
```

**Comment by satanshiro** [comment] 2024-05-19 14:34
I created a monorepo setup with nx where it works: https://github.com/satanshiro/keycloakify-starter
I cannot understand how 'dummy-non-existing-folder' as it does not occur in this setup,
but I will say that keycloakify requires a package json to reside within the child path as it assumes it is the root folder,
if you delete the inner (empty) package.json file you will get an error. another thing is that also it still created the vite.json within the child folder

**Comment by garronej** [comment] 2024-05-19 21:23
Hello @satanshiro,  

Thank you for putting together a reproduction repo.  
Unfortunately I'm unable to reproduce.  
There is indeed a bug in that Keycloakify does not successfully figure out the root of your monorepo. It'll be fixed in next release however it's not the rook of the problem here. It just creates the cache directory within `apps/keycloakify-nx/node_modules/.cache/keycloakify` insted of `node_modules/.cache/keycloakify`.  

After futher investigation I think the issue you are facing might be related to the `XDG_CACHE_HOME` environement variable.  

Can you check if it's set to `XDG_CACHE_HOME`.  

Maybe `console.log(process.env["XDG_CACHE_HOME"])` alongside the other logs that you have added.  
This would start explaining things.

**Comment by satanshiro** [comment] 2024-05-20 13:53
the env var XDG_CACHE_HOME  is undefined.
In a bizarre way on a coworker environment the 'dummy-non-existing-folder' does not show up i'm still investigating this one in any case thanks for your answer, also notice again that keycloakify made the same mistake in regards to package.json location. in the repo i made try removing the package.json file located under apps/keycloakify-nx folder and notice an error on build (.nx cache folder needs to be deleted)

**Comment by garronej** [comment] 2024-05-23 13:47
Okay that's something...  
However Vitest isn't a dependency of the reproduction repo your provided: https://github.com/satanshiro/keycloakify-starter  
Even if I add it I still can't reproduce.  

Can you try again from scratch from your reproduction repo to tell if you can reproduce the error?  
Make sure to add Vitest a dependency so you don't use your local version.  
If you can reproduce please provide me the exact command you typed.  

Best

**Comment by garronej** [comment] 2024-06-24 05:11
Hello @satanshiro,  

Everything works now winth Keycloakify 10 :)  

https://github.com/satanshiro/keycloakify-starter/pull/1

**Comment by garronej** [comment] 2024-06-30 16:05
@satanshiro there is now a page in the documentation dedicated to integration with Nx.  
https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo/nx-integrated-monorepo  

Let me know if you think it could be improved.  

In the meantime, I'll close this.  

Thank you for your help on this

**Closed by garronej** 2024-06-30 16:05 UTC

**Comment by satanshiro** [comment] 2024-06-30 16:47
@garronej thank you very much! appreciate the work a lot cant't wait to upgrade to keycloak 25 along with keycloakify v10!
