### ISSUE TITLE
Yarn Install fails

### ISSUE THREAD

**Issue by masquerade75** [keycloakify/keycloakify#328] opened 2023-04-20 09:15 UTC
Hi, I tried installing the starter project on Windows 10 and I get this error while fecthing  https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip

C:\Projects\Eclipse\Tests\keycloakify-starter\node_modules\minipass-fetch\lib\index.js:130
      reject(new FetchError(`request to ${request.url} failed, reason: ${
             ^

FetchError: request to https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Projects\Eclipse\Tests\keycloakify-starter\node_modules\minipass-fetch\lib\index.js:130:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  type: 'system'
}

Node.js v18.16.0
error Command failed with exit code 1.

I have tried to set strict ssl to false with no luck.
In fact, https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip points to a link with certificate issues

Thank you

**Comment by garronej** [comment] 2023-04-20 09:18
Hi @masquerade75,  

It's yarn install that fails?

**Comment by garronej** [comment] 2023-04-20 09:20
If you comment out this line of the package.json: https://github.com/keycloakify/keycloakify-starter/blob/6c00e04a2654c0509fd9413dc18f58126298142e/package.json#L11 wats up?

**Comment by masquerade75** [comment] 2023-04-20 10:04
It works, but then it fails with the same error while running build-keycloak-theme

 Building the keycloak theme...⌚
C:\Projects\Eclipse\Tests\keycloakify-starter\node_modules\minipass-fetch\lib\index.js:130
      reject(new FetchError(`request to ${request.url} failed, reason: ${
             ^

FetchError: request to https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Projects\Eclipse\Tests\keycloakify-starter\node_modules\minipass-fetch\lib\index.js:130:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  type: 'system'
}

Node.js v18.16.0
error Command failed with exit code 1.

**Comment by garronej** [comment] 2023-04-20 10:16
The error you are encountering, "FetchError: request to https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip failed, reason: unable to get local issuer certificate" is related to SSL/TLS certificates. This error usually occurs when the client (in this case, minipass-fetch) is unable to validate the SSL/TLS certificate of the server (in this case, GitHub) because it cannot find the certificate of the Certificate Authority (CA) that issued the server certificate.

Here are a few possible solutions:

1 Update your Node.js version: Older versions of Node.js might not have the latest CA certificates. Updating Node.js to the latest LTS version might resolve the issue.


2 Eddit the package.json script
```diff
-"build-keycloak-theme": "yarn build && keycloakify"
+"build-keycloak-theme": "yarn build && export NODE_TLS_REJECT_UNAUTHORIZED='0' keycloakify"
```

**Comment by masquerade75** [comment] 2023-04-20 11:17
None of the two solutions work, I upgraded node to 20.0 but I get same error

**Comment by masquerade75** [comment] 2023-04-20 16:38
Yes I tried also yarn config (with -g flag), still doesn't work

**Comment by lordvlad** [comment] 2023-04-23 07:34
I'd also suspect a proxy issue. I also remember that npm on windows often had issues with TLS but that was a long time ago. What versions of node and npm do you use @masquerade75 ?

**Comment by lordvlad** [comment] 2023-04-23 07:38
@garronej I think I mentioned it once but I'd love to introduce https://www.npmjs.com/package/debug to help with these issues. We could define a number of log levels to help us see what's up

**Comment by willwill96** [comment] 2023-04-23 19:36
I agree it is likely a proxy or vpn issue. Yarn is supposed to respect all `.npmrc`, but I've seen cases where it doesn't pick everything up properly. It might be worth setting the strict ssl options through yarn instead?

yarn 1:

```
yarn config set "strict-ssl" false -g
```

yarn 2+:

```
yarn config set enableStrictSsl false
```

**Comment by masquerade75** [comment] 2023-04-23 20:30
I use 
Node 20.0.0
and 
npm 9.6.4

and 

if I run ~\.npmrc

strict-ssl=false
cafile=C:\Projects\Eclipse\Tests\keycloakify-starter\null
registry=http://registry.npmjs.org/

**Comment by willwill96** [comment] 2023-04-23 21:12
I don't think you want the cafile definition @masquerade75

**Comment by lordvlad** [comment] 2023-04-23 21:43
Keycloakify won't pick custom CA or SSL config from npmrc, only proxy. Maybe that's the issue? You have an SSL proxy with a company certificate? Since yarn and npm use full npmrc config the installation works but since keycloakify build uses fetch, which needs to be configured by keycloakify code, the download fails?

Can you confirm if you have a proxy set up or vpn? Can you use curl or wget to download the zip? E.g. `wget https://github.com/keycloak/keycloak/archive/refs/tags/11.0.3.zip`

**Comment by lordvlad** [comment] 2023-04-24 10:03
@garronej whoops, now we  havethe same issue in CI? https://github.com/keycloakify/keycloakify/actions/runs/4784976215/jobs/8507141652?pr=332

**Comment by garronej** [comment] 2023-04-24 11:14
Well at least we can reproduce 😬

**Comment by garronej** [comment] 2023-04-24 15:16
Hey there,

It appears that the development of Keycloakify has been slowed down by some unexpected issues. 
I have to admit, I'm a bit puzzled. If you have any advice or suggestions, I'd really appreciate your help.

**Comment by lordvlad** [comment] 2023-04-25 06:19
This issue is not reproducible anymore on ci, so we're back at a likely configuration issue.

I've started work on improved logging to get to the root. @masquerade75 if you could checkout [this pr](https://github.com/keycloakify/keycloakify/pull/335)of keycloakify and run `DEBUG='keycloakify:debug:*' yarn` (Unix/Mac) or `$env:DEBUG='keycloakify:debug:*; yarn` (win Powershell) in the project root, and report the output it might be helpful

**Comment by masquerade75** [comment] 2023-04-26 09:17
Here's the output after checking out the pull request

PS C:\Projects\Eclipse\Tests\keycloakify> yarn --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@storybook/addon-actions > react-inspector@5.1.1" has incorrect peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has incorrect peer dependency "react@^16.13.1 || ^17.0.0".
warning " > @storybook/react@6.5.16" has unmet peer dependency "require-from-string@^2.0.2".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/react > react-element-to-jsx-string@14.3.4" has incorrect peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning " > eslint-plugin-storybook@0.6.11" has unmet peer dependency "eslint@>=6".
warning "eslint-plugin-storybook > @typescript-eslint/utils@5.59.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || ^8.0.0".
warning "eslint-plugin-storybook > @typescript-eslint/utils > @eslint-community/eslint-utils@4.4.0" has unmet peer dependency "eslint@^6.0.0 || ^7.0.0 || >=8.0.0".
[4/4] Building fresh packages...
$ yarn generate-i18n-messages
yarn run v1.22.19
$ ts-node --skipProject scripts/generate-i18n-messages.ts
  keycloakify:info:generate-i18n-messages Generating i18n message files from keycloak 21.0.1 sources +0ms
C:\Projects\Eclipse\Tests\keycloakify\node_modules\minipass-fetch\lib\index.js:130
      reject(new FetchError(`request to ${request.url} failed, reason: ${
             ^
FetchError: request to https://github.com/keycloak/keycloak/archive/refs/tags/21.0.1.zip failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Projects\Eclipse\Tests\keycloakify\node_modules\minipass-fetch\lib\index.js:130:14)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:523:35)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  type: 'system'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by lordvlad** [comment] 2023-04-26 19:56
@masquerade75 this is missing the debug output. Can you run  `$en:DEBUG='keycloakify:debug:*`; yarn --frozen lockfile`?

**Comment by masquerade75** [comment] 2023-04-29 18:42
This is the output

PS C:\Projects\Eclipse\Tests\keycloakify> git checkout feat/logging
Already on 'feat/logging'
Your branch is up to date with 'origin/feat/logging'.

PS C:\Projects\Eclipse\Tests\keycloakify> git pull
Already up to date.

PS C:\Projects\Eclipse\Tests\keycloakify> $env:DEBUG='keycloakify:debug:*'; yarn
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
$ yarn generate-i18n-messages
yarn run v1.22.19
$ ts-node --skipProject scripts/generate-i18n-messages.ts
  keycloakify:info:generate-i18n-messages Generating i18n message files from keycloak 21.0.1 sources +0ms
C:\Projects\Eclipse\Tests\keycloakify\node_modules\minipass-fetch\lib\index.js:130
      reject(new FetchError(`request to ${request.url} failed, reason: ${
             ^
FetchError: request to https://github.com/keycloak/keycloak/archive/refs/tags/21.0.1.zip failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Projects\Eclipse\Tests\keycloakify\node_modules\minipass-fetch\lib\index.js:130:14)
    at ClientRequest.emit (node:events:511:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:523:35)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  type: 'system'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by garronej** [comment] 2024-02-07 23:55
I think it should be fixed. Please reopen if it isn't

**Closed by garronej** 2024-02-07 23:55 UTC
