### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by ar7casper** [keycloakify/keycloakify#405] opened 2023-08-24 09:25 UTC
Hi,

I'm using a monorepo setup (nx, but it doesn't really matter in this case).
My app is at route `app/foo/src`.
When I run `npx keycloakify` it assumes that everything is in the same folder, meaning `./src/`

It would be great if we could pass in an option to set the root of the app.
In addition, I need to be able to pass in the `dist` folder as well.

Relevant places - 
eject-keycloak-page.ts

Line 52:   
```
 const { themeSrcDirPath } = getThemeSrcDirPath({ "projectDirPath": process.cwd() });
```

**Comment by garronej** [comment] 2023-08-24 11:16
Hello @ar7casper,

Thank you for bringing this to our attention.

We're aware that many users are working with monorepos, but there could be lingering issues, particularly with the eject-keycloak-page script. Since this script is still in its experimental stage, I would recommend manually copying and pasting the code if you encounter any issues using it.

In addition to the concerns about eject-keycloak-page, could you please elaborate on the specific difficulties you're facing with the keycloakify script?

Creating a minimal reproduction repository to demonstrate the issue would be incredibly helpful for us to understand and resolve the problem more effectively.

Thank you for your cooperation.

Best regards,

**Comment by ar7casper** [comment] 2023-08-28 11:09
In case anyone needs a workaround - 

I copy the package.json to the target app and then then the `dist` into the app's `build`.
Then I `cd` into it and run `npx keycloackify`

**Comment by garronej** [comment] 2023-08-28 15:46
Thanks for sharing your workaroud!
Don't hesitate to produce a reproduction repo if you want a proper fix.  

Best,  

Closing, but feel free to reopen with any aditional infos

**Closed by garronej** 2023-08-28 15:46 UTC

**Comment by garronej** [comment] 2024-06-30 16:08
@ar7casper There is now a section in the documentation for Keycloakify v10 dedicated to monorepos integration:  

https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo

**Comment by ar7casper** [comment] 2024-07-01 05:00
The client shut down the company in the mean time 😎
