### ISSUE TITLE
ENOWORKSPACES error when being used with yarn workspaces

### ISSUE THREAD

**Issue by squishyu** [keycloakify/keycloakify#380] opened 2023-07-13 07:54 UTC
We're trying to integrate keycloakify into our monorepo using yarn workspaces so we can use shared components for a consistent style.
However, when using Node 18.14+ (specifically caused by using NPM 9+), we get the ENOWORKSPACES error due to the usage of `npm config get`.

```
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in: /home/squishyu/.npm/_logs/2023-07-13T07_38_57_081Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm config get',
  stdout: '',
  stderr: 'npm ERR! code ENOWORKSPACES\n' +
    'npm ERR! This command does not support workspaces.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in: /home/squishyu/.npm/_logs/2023-07-13T07_38_57_081Z-debug-0.log\n'
}

Node.js v18.16.0
```

The command in question is being used at [/src/bin/tools/downloadAndUnzip.ts:52](https://github.com/keycloakify/keycloakify/blob/7214dbccdbb4c366c8c327f9882c0064cdc265c2/src/bin/tools/downloadAndUnzip.ts#L52)

I saw discussion about switching from `npm config` in a [different issue](https://github.com/keycloakify/keycloakify/issues/284#issuecomment-1492894837) (#284)

Any updates on fixing this?

**Comment by garronej** [comment] 2023-07-13 09:49
Damn, sorry about that! 
Maybe try the build option `"bundler": "mvn"` as a temporary fix? https://docs.keycloakify.dev/build-options#bundler  

Thanks for reporting.  

Hi @lordvlad, is this an easy fix or a hard fix?

**Comment by ddubrava** [comment] 2023-07-24 09:00
HI! I get the same error on `npx keycloakify`

```
🔏 Building the keycloak theme...⌚
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-24T08_56_46_683Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm config get',
  stdout: '',
  stderr: 'npm ERR! code ENOWORKSPACES\n' +
    'npm ERR! This command does not support workspaces.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-24T08_56_46_683Z-debug-0.log\n'
}

Node.js v18.16.0
```

**Comment by garronej** [comment] 2023-07-24 11:42
If you can provide a reproduction repo I can fix this quick

**Comment by squishyu** [comment] 2023-07-24 13:05
I created a simple reproduction repo based on the [keycloakify-starter](https://github.com/keycloakify/keycloakify-starter) repository:

https://github.com/squishyu/keycloakify-workspaces-bug

**Comment by garronej** [comment] 2023-07-24 21:07
The fix is trivial. I'm on it.

**Comment by garronej** [comment] 2023-07-24 21:41
Fixed in 7.15.3. Thanks for the reproduction repo and sorry it took me two week to adress this.

**Closed by garronej** 2023-07-24 21:41 UTC

**Comment by squishyu** [comment] 2023-07-25 12:48
Seems to work great! Coworker found your solution hilarious.

**Comment by garronej** [comment] 2023-07-25 15:01
Great :))

Indeed, the solution can be somewhat intricate, I will concede. It's worth noting that this particular section of the codebase wasn't authored by me. I intended to modify only the function that was causing issues.

**Comment by ddubrava** [comment] 2023-07-25 15:33
it works pretty weird, since I get the same error if I reinstall modules. Then I run it again, it everything works.

```
/Users/ddubrava/.nvm/versions/node/v18.16.0/bin/npm run build-keycloak-theme

> build-keycloak-theme
> rm -rf build && rm -rf build_keycloak && npm run build && keycloakify


> build
> npm run webpack


> webpack
> cross-env TS_NODE_PROJECT='../tsconfig-for-webpack-config.json' webpack

assets by path *.js 3.59 MiB
  assets by chunk 493 KiB (id hint: vendors) 24 assets
  + 24 assets
asset 7cd80027de24cbc2280b.svg 9.29 KiB [emitted] [immutable] [from: src/login/assets/background.svg] (auxiliary name: main)
asset index.html 234 bytes [emitted]
orphan modules 5.53 MiB [orphan] 1198 modules
runtime modules 6.18 KiB 11 modules
cacheable modules 3.12 MiB (javascript) 9.29 KiB (asset)
  modules by path ../node_modules/ 2.81 MiB 288 modules
  modules by path ../packages/ 276 KiB 101 modules
  modules by path ./src/ 28.2 KiB (javascript) 9.29 KiB (asset)
    modules by path ./src/login/*.ts 3.72 KiB 2 modules
    modules by path ./src/login/*.tsx 13.6 KiB 2 modules
    modules by path ./src/login/*.css 2.86 KiB 2 modules
    + 3 modules
  modules by path ../common/ 20 KiB
    ../common/const/lang-en.ts 19.4 KiB [built] [code generated]
    ../common/entities/InviteAccessLevel.ts 278 bytes [built] [code generated]
    ../common/entities/WebNetworkStatus.ts 283 bytes [built] [code generated]
webpack 5.75.0 compiled successfully in 4866 ms
🔏 Building the keycloak theme...⌚
Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log
 Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm config get',
  stdout: '',
  stderr: 'npm ERR! code ENOWORKSPACES\n' +
    'npm ERR! This command does not support workspaces.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log\n'
}
Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log
 Error: Command failed: npm config get
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm config get',
  stdout: '',
  stderr: 'npm ERR! code ENOWORKSPACES\n' +
    'npm ERR! This command does not support workspaces.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/ddubrava/.npm/_logs/2023-07-25T15_29_26_415Z-debug-0.log\n'
}
```

but actually sometimes it doesn't work even for the second time and I get this error `yauzl/index.js:187 callback(new Error("end of central directory record signature not found"));`, and only after 3-5 node modules installs it works

**Comment by ddubrava** [comment] 2023-07-28 09:17
I can't reproduce this outside of our project. The only difference from the repo above  is that our project depends on another workspace (`"test": "*"`). Here is the log, if you need it

[log.txt](https://github.com/keycloakify/keycloakify/files/12192538/log.txt)

**Comment by ddubrava** [comment] 2023-08-19 23:49
@garronej Hi! We faced with a few issues that force us to use workspaces, so I'm debugging this again. Currently, it works ok, But this error that you log (https://github.com/keycloakify/keycloakify/blob/476a33c0abfe87e91c45242371c7b8a34014d7ed/src/bin/tools/downloadAndUnzip.ts#L60), can we remove it? It doesn't make any sense, you see this 20 lines error and the build goes on

**Comment by garronej** [comment] 2023-08-20 00:31
Ohh... of course sory. I though I removed this console.log!

**Comment by garronej** [comment] 2024-06-30 16:09
Hi @squishyu and @ddubrava,  

Keycloakify 10 now officially suport Monorepos.  

Here is the documentation section: https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo  

Let me know if it fits your needs.

**Comment by ddubrava** [comment] 2024-06-30 16:17
> Hi @squishyu and @ddubrava,
> 
> Keycloakify 10 now officially suport Monorepos.
> 
> Here is the documentation section: https://docs.keycloakify.dev/keycloakify-in-my-app/as-a-subproject-of-your-monorepo
> 
> Let me know if it fits your needs.

Hi! Thank you! <10 are also fine; we haven't run into any issues
