### ISSUE TITLE
Email verification link reloads the page without confirming email

### ISSUE THREAD

**Issue by pashaeryshken** [keycloakify/keycloakify#664] opened 2024-09-19 20:44 UTC
### Description:
When I receive an email verification link and open it in a different browser or in incognito mode (where no session exists), I follow the link to confirm my email. Upon clicking the confirmation button, the page simply reloads instead of completing the email verification, and I am brought back to the same step without any progress.

### Steps to Reproduce:
1. In Keycloak, enable **Email verification** as a required action during user registration.
2. Register a new user with an email that requires verification.
3. Open the verification link from the email in a different browser or in **Incognito Mode** (where there is no existing session).
4. The page displays a button to confirm the email.
5. Click the "Confirm email" button.

### Expected Behavior:
- The email should be verified, and the user should proceed to the next step in the registration process or login flow.

### Actual Behavior:
- After clicking the "Confirm email" button, the page reloads, and the user is redirected back to the same confirmation step. The email is not verified, and the process does not move forward.

### Affected Version(s):
- Keycloakify version: 10.1.4
- Keycloak version: 25

### Additional Context:
This issue appears to be related to scenarios where there is no active session in the browser used to open the email confirmation link (e.g., in incognito mode or another browser).

**Comment by garronej** [comment] 2024-09-19 20:48
Thank you for opening the issue I'll try to reproduce and see what's up

**Comment by garronej** [comment] 2024-09-19 20:53
Can't reproduce, at least with Keycloakify 10.0.0-rc.59 wich is the version that we currently have in production with Keycloak 25.

**Comment by garronej** [comment] 2024-09-19 20:53
I'll try with the latest vesion

**Comment by pashaeryshken** [comment] 2024-09-19 23:21
Yes, it worked. I created a new project and tested it. Now I'll think about why it didn't work in my old code.

**Comment by garronej** [comment] 2024-09-20 00:51
Ok so I guess I can close the issue :)

**Closed by garronej** 2024-09-20 00:51 UTC
